name: example
description: A new Flutter application.

version: 1.0.0+1
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  avatar_glow:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar.png
    - assets/images/flutter.png
    - assets/images/love.png
    - assets/images/dart.png
