name: Misc on Prod Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: 'Create a new release'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 'Extract changelog'
        id: extract-changelog
        uses: TheDotLabs/extract-release-notes@main

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.extract-changelog.outputs.release_notes }}
          token: ${{ secrets.GITHUB_TOKEN }}
